version: '3.7'
services:
  postgres:
    # hostname: pgsql
    # container_name: pgsql
    image: "postgres:alpine"
    # image: postgres:11-alpine
    # image: postgres:10-alpine
    # image: postgres:9.6-alpine
    environment:
      #POSTGRES_HOST_AUTH_METHOD: "trust"
      #POSTGRES_DB: ${DB_NAME:-sample}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-25432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # restart: always
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

volumes:
  pgsqldata:
  pgadmin:
